- hosts: all

  vars:
    - source_dir: /software/source
    - soft_dir: /software/apps
    - modules_dir: /software/modules
    - brew_dir: /software/linuxbrew
    - ref_dir: /references

  tasks:
    - include: tasks/common-packages.yml
    - include: tasks/zsh.yml
    - include: tasks/lmod.yml lmod_version=5.8.6
    - include: tasks/java.yml
    - include: tasks/r-packages.yml
 
    - include: tasks/linuxbrew.yml tags=linuxbrew

    - include: tasks/SPAdes.yml tags=spades
    - include: tasks/bwa.yml tags=bwa
    - include: tasks/STAR.yml tags=star version=2.4.0j
    - include: tasks/picard.yml tags=picard version=1.129
    - include: tasks/htslib.yml tags=htslib version=1.2
    - include: tasks/samtools.yml tags=samtools version=1.2 htslib_version=1.2
    - include: tasks/bcftools.yml tags=bcftools version=1.2
    - include: tasks/cufflinks.yml tags=cufflinks version=2.2.1
    - include: tasks/tophat.yml tags=tophat version=2.0.13
    - include: tasks/ncbi-blast.yml tags=ncbi-blast version=2.2.30
    - include: tasks/vcftools.yml tags=vcftools version=0.1.12b
    - include: tasks/igvtools.yml tags=igvtools version=2.3.42
    - include: tasks/igv.yml tags=igv version=2.3.42
    - include: tasks/gatk.yml tags=gatk version=3.3-0
    - include: tasks/bowtie.yml tags=bowtie1 version=1.1.1
    - include: tasks/bowtie2.yml tags=bowtie2 version=2.2.5
    - include: tasks/trinity.yml tags=trinity version=2.0.6
    - include: tasks/velvet.yml tags=velvet version=1.2.10
    - include: tasks/hmmer.yml tags=hmmer version=3.1b2
    - include: tasks/bedops.yml tags=bedops version=2.4.11
    - include: tasks/blat.yml tags=blat version=35
    - include: tasks/hisat.yml tags=hisat version=0.1.5-beta
    - include: tasks/homer.yml tags=homer
    - include: tasks/bamutil.yml tags=bamutil version=1.0.13
    - include: tasks/bamstats.yml tags=bamstats version=1.25
    - include: tasks/trimmomatic.yml tags=trimmomatic version=0.33
    - include: tasks/rstudio-server.yml tags=rstudio version=0.98.1103-amd64
    - include: tasks/rna-seqc.yml tags=rna-seqc version=1.1.8
    - include: tasks/big-data-script.yml tags=big-data-script version=0.999h
    - include: tasks/rseqc.yml tags=rseqc version=2.6.1
    - include: tasks/artemis.yml tags=artemis version=16.0.0

    - include: tasks/macs2.yml tags=macs2 version=2.1.0.20140616

    - include: tasks/prokka.yml tags=prokka
    - include: tasks/misc_utils.yml tags=misc_utils

    - pip: name=htseq
    - pip: name=pysam
    - pip: name=nesoni
