- hosts: all

  vars:
    - source_dir: /software/source
    - soft_dir: /software/apps
    - modules_dir: /software/modules

  tasks:
    - include: tasks/common-packages.yml
    - include: tasks/zsh.yml
    - include: tasks/lmod.yml lmod_version=5.8.6
    - include: tasks/java.yml
    - include: tasks/r-packages.yml


    - include: tasks/SPAdes.yml
    - include: tasks/BWA.yml
    - include: tasks/STAR.yml version=2.4.0j
    - include: tasks/picard.yml version=1.129
    - include: tasks/htslib.yml version=1.2
    - include: tasks/samtools.yml version=1.2 htslib_version=1.2
    - include: tasks/cufflinks.yml version=2.2.1
    - include: tasks/tophat.yml version=2.0.13
    - include: tasks/ncbi-blast.yml version=2.2.30
    - include: tasks/vcftools.yml version=0.1.12b
    - include: tasks/igvtools.yml version=2.3.42
    - include: tasks/igv.yml version=2.3.42

    - pip: name=htseq
    - pip: name=nesoni
