- name: Git Clone RNAsik-pipe
  git: repo=https://github.com/serine/bdsRNAseqPipeline.git
       dest={{ soft_dir }}/RNAsik-pipe-4629260
       version=46292608c49a3bf6400d794b10cfd5885965500e
       update=no

- file: dest="{{modules_dir}}/bio/RNAsik-pipe" state=directory mode=0755

- name: RNAsik-pipe module definition
  template: 
    src: templates/sw-module.lua.j2 
    dest: "{{ modules_dir }}/bio/RNAsik-pipe/4629260.lua"
    owner: root 
    mode: 0644
  with_items:
    - { help_text: 'This module loads Kirill RNAsik-pipe', dir: 'RNAsik-pipe-4629260', skip_bin: true }
